fullnameOverride: location-rider

namespace:
  name: microgo-dev

global:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

component:
  name: location-rider
  fullnameOverride: location-rider
  replicaCount: 1
  containerPort: 8083
  image:
    repository: registry.digitalocean.com/hendafarhani-microgo-registry/microgo-location-rider
    tag: latest
  service:
    enabled: true
    type: ClusterIP
    port: 8083
    targetPort: 8083
  configMap:
    enabled: true
    data:
      SPRING_CLOUD_CONFIG_URI: http://centralized-config:8080
      SPRING_CLOUD_CONFIG_NAME: location-rider
      SPRING_CONFIG_IMPORT: optional:configserver:http://centralized-config:8080
  secret:
    enabled: false
    stringData: {}
  env:
    - name: SERVER_PORT
      value: "8083"
    - name: PORT
      value: "8083"
  readinessProbe:
    tcpSocket:
      port: 8083
    initialDelaySeconds: 20
    periodSeconds: 10
  livenessProbe:
    tcpSocket:
      port: 8083
    initialDelaySeconds: 40
    periodSeconds: 15
  resources: {}
