apiVersion: v2
name: driver-location-streamer
description: Helm chart for the driver-location-streamer service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
