fullnameOverride: driver-location-streamer

namespace:
  name: microgo-dev

global:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

component:
  name: driver-location-streamer
  fullnameOverride: driver-location-streamer
  replicaCount: 1
  containerPort: 8085
  image:
    repository: registry.digitalocean.com/hendafarhani-microgo-registry/microgo-driver-location-streamer
    tag: latest
  service:
    enabled: true
    type: ClusterIP
    port: 8085
    targetPort: 8085
  configMap:
    enabled: true
    data:
      SPRING_CLOUD_CONFIG_URI: http://centralized-config:8080
      SPRING_CLOUD_CONFIG_NAME: driver-location-streamer
      SPRING_CONFIG_IMPORT: optional:configserver:http://centralized-config:8080
  secret:
    enabled: false
    stringData: {}
  env:
    - name: SERVER_PORT
      value: "8085"
    - name: PORT
      value: "8085"
  readinessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 20
    periodSeconds: 10
  livenessProbe:
    tcpSocket:
      port: 8085
    initialDelaySeconds: 40
    periodSeconds: 15
  resources: {}
