#!/usr/bin/env bash
set -Eeuo pipefail

if [[ -z "${POSTGRES_DATABASES:-}" ]]; then
  echo "POSTGRES_DATABASES is empty; no service databases to create."
  exit 0
fi

IFS=',' read -ra databases <<< "${POSTGRES_DATABASES}"

create_driver_location_tables() {
  psql \
    --set=ON_ERROR_STOP=1 \
    --username "${POSTGRES_USER}" \
    --dbname "$1" <<-'SQL'
CREATE TABLE IF NOT EXISTS driver_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_identifier VARCHAR(255) NOT NULL UNIQUE,
    driver_display_id VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
SQL
}

create_simulation_service_tables() {
  psql \
    --set=ON_ERROR_STOP=1 \
    --username "${POSTGRES_USER}" \
    --dbname "$1" <<-'SQL'
CREATE TABLE IF NOT EXISTS scenario_config (
    id UUID PRIMARY KEY,
    scenario_name VARCHAR(64) NOT NULL UNIQUE,
    city VARCHAR(64) NOT NULL,
    anchor_zone VARCHAR(64) NOT NULL,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    weather VARCHAR(32) NOT NULL,
    traffic_level VARCHAR(32) NOT NULL,
    passenger_demand_multiplier NUMERIC(8,4) NOT NULL,
    cancellation_risk_multiplier NUMERIC(8,4) NOT NULL,
    driver_speed_multiplier NUMERIC(8,4) NOT NULL,
    airport_fare_bias NUMERIC(8,4) NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS simulation_run (
    id UUID PRIMARY KEY,
    scenario_config_id UUID NOT NULL REFERENCES scenario_config(id),
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    requested_by VARCHAR(128),
    notes VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS passenger_profile (
    id UUID PRIMARY KEY,
    simulation_run_id UUID NOT NULL REFERENCES simulation_run(id),
    external_passenger_id VARCHAR(64) NOT NULL UNIQUE,
    origin_zone VARCHAR(64) NOT NULL,
    destination_zone VARCHAR(64) NOT NULL,
    urgency_score NUMERIC(8,4) NOT NULL,
    cancellation_sensitivity NUMERIC(8,4) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS driver_profile (
    id UUID PRIMARY KEY,
    simulation_run_id UUID NOT NULL REFERENCES simulation_run(id),
    external_driver_id VARCHAR(64) NOT NULL UNIQUE,
    home_zone VARCHAR(64) NOT NULL,
    fatigue_score NUMERIC(8,4) NOT NULL,
    airport_preference NUMERIC(8,4) NOT NULL,
    destination_bias VARCHAR(64) NOT NULL,
    reliability_score NUMERIC(8,4) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS simulation_metrics (
    id UUID PRIMARY KEY,
    simulation_run_id UUID NOT NULL REFERENCES simulation_run(id),
    pending_ride_requests INTEGER NOT NULL,
    accepted_rides INTEGER NOT NULL,
    refused_rides INTEGER NOT NULL,
    cancelled_rides INTEGER NOT NULL,
    average_waiting_time_seconds NUMERIC(10,2) NOT NULL,
    cancellation_risk NUMERIC(8,4) NOT NULL,
    acceptance_probability NUMERIC(8,4) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS simulation_result (
    id UUID PRIMARY KEY,
    simulation_run_id UUID NOT NULL UNIQUE REFERENCES simulation_run(id),
    active_scenario VARCHAR(64) NOT NULL,
    predicted_demand_by_zone JSONB NOT NULL,
    pending_ride_requests INTEGER NOT NULL,
    driver_acceptance_probability NUMERIC(8,4) NOT NULL,
    average_waiting_time_seconds NUMERIC(10,2) NOT NULL,
    cancellation_risk NUMERIC(8,4) NOT NULL,
    metrics_snapshot JSONB NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL
);
SQL
}

create_optimization_service_tables() {
  psql \
    --set=ON_ERROR_STOP=1 \
    --username "${POSTGRES_USER}" \
    --dbname "$1" <<-'SQL'
CREATE TABLE IF NOT EXISTS optimization_run (
    id UUID PRIMARY KEY,
    simulation_run_id UUID NOT NULL,
    scenario VARCHAR(64) NOT NULL,
    trigger_source VARCHAR(64) NOT NULL,
    solver_status VARCHAR(64) NOT NULL,
    snapshot_generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    baseline_strategy VARCHAR(64) NOT NULL,
    optimization_strategy VARCHAR(64) NOT NULL,
    score_summary TEXT
);

CREATE TABLE IF NOT EXISTS optimization_result (
    id UUID PRIMARY KEY,
    optimization_run_id UUID NOT NULL REFERENCES optimization_run(id),
    driver_count INTEGER NOT NULL,
    pending_ride_count INTEGER NOT NULL,
    demand_summary JSONB NOT NULL,
    baseline_metrics JSONB NOT NULL,
    optimized_metrics JSONB NOT NULL,
    score_hard INTEGER,
    score_soft INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS baseline_vs_optimized_metrics (
    id UUID PRIMARY KEY,
    optimization_run_id UUID NOT NULL REFERENCES optimization_run(id),
    metric_name VARCHAR(128) NOT NULL,
    baseline_value NUMERIC(12,4) NOT NULL,
    optimized_value NUMERIC(12,4) NOT NULL,
    improvement NUMERIC(12,4) NOT NULL,
    unit VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS driver_repositioning_recommendation (
    id UUID PRIMARY KEY,
    optimization_run_id UUID NOT NULL REFERENCES optimization_run(id),
    driver_id VARCHAR(128) NOT NULL,
    current_zone VARCHAR(64) NOT NULL,
    target_zone VARCHAR(64) NOT NULL,
    distance_km NUMERIC(8,3) NOT NULL,
    priority_score NUMERIC(8,4) NOT NULL,
    expected_wait_reduction_seconds INTEGER,
    expected_cancellation_reduction NUMERIC(8,4),
    recommendation_status VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_optimization_run_simulation_run
    ON optimization_run(simulation_run_id);

CREATE INDEX IF NOT EXISTS idx_driver_repositioning_recommendation_driver
    ON driver_repositioning_recommendation(driver_id);
SQL
}

for database in "${databases[@]}"; do
  database="${database//[[:space:]]/}"

  if [[ -z "${database}" ]]; then
    continue
  fi

  echo "Ensuring PostgreSQL database '${database}' exists."

  psql \
    --set=ON_ERROR_STOP=1 \
    --set=database_name="${database}" \
    --set=database_owner="${POSTGRES_USER}" \
    --username "${POSTGRES_USER}" \
    --dbname "${POSTGRES_DB}" <<-'SQL'
SELECT format('CREATE DATABASE %I OWNER %I', :'database_name', :'database_owner')
WHERE NOT EXISTS (
    SELECT 1
    FROM pg_database
    WHERE datname = :'database_name'
)
\gexec
SQL

  case "${database}" in
    driver_location)
      echo "Ensuring PostgreSQL tables for driver-location-generator exist in '${database}'."
      create_driver_location_tables "${database}"
      ;;
    simulation_service)
      echo "Ensuring PostgreSQL tables for simulation-service exist in '${database}'."
      create_simulation_service_tables "${database}"
      ;;
    optimization_service)
      echo "Ensuring PostgreSQL tables for optimization-service exist in '${database}'."
      create_optimization_service_tables "${database}"
      ;;
  esac
done
