apiVersion: v2
name: ride-request
description: Helm chart for the ride-request service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../common"
